# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sales.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'sales.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bsales.proto\x12\x0bsalesstream\"c\n\x0bSalesRecord\x12\x0f\n\x07sale_id\x18\x01 \x01(\t\x12\x14\n\x0cproduct_name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x02\x12\x0c\n\x04\x64\x61te\x18\x05 \x01(\t\"L\n\rUploadSummary\x12\x13\n\x0btotal_sales\x18\x01 \x01(\x05\x12\x15\n\rtotal_revenue\x18\x02 \x01(\x02\x12\x0f\n\x07message\x18\x03 \x01(\t2V\n\rSalesStreamer\x12\x45\n\x0bUploadSales\x12\x18.salesstream.SalesRecord\x1a\x1a.salesstream.UploadSummary(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sales_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SALESRECORD']._serialized_start=28
  _globals['_SALESRECORD']._serialized_end=127
  _globals['_UPLOADSUMMARY']._serialized_start=129
  _globals['_UPLOADSUMMARY']._serialized_end=205
  _globals['_SALESSTREAMER']._serialized_start=207
  _globals['_SALESSTREAMER']._serialized_end=293
# @@protoc_insertion_point(module_scope)
