# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sales_pb2 as sales__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sales_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SalesStreamerStub(object):
    """Define the sales information service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadSales = channel.stream_unary(
                '/salesstream.SalesStreamer/UploadSales',
                request_serializer=sales__pb2.SalesRecord.SerializeToString,
                response_deserializer=sales__pb2.UploadSummary.FromString,
                _registered_method=True)


class SalesStreamerServicer(object):
    """Define the sales information service
    """

    def UploadSales(self, request_iterator, context):
        """Client streaming RPC to send sales information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SalesStreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadSales': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadSales,
                    request_deserializer=sales__pb2.SalesRecord.FromString,
                    response_serializer=sales__pb2.UploadSummary.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'salesstream.SalesStreamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('salesstream.SalesStreamer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SalesStreamer(object):
    """Define the sales information service
    """

    @staticmethod
    def UploadSales(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/salesstream.SalesStreamer/UploadSales',
            sales__pb2.SalesRecord.SerializeToString,
            sales__pb2.UploadSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
